### ISSUE TITLE
The using requirement of mHapTools

### ISSUE THREAD

**Issue by EnyangQiao** [butyuhao/mHapTools#1]
Hi, I have a question about the tool mHapTools. I used the alignment results to do methylation haplotypes by mHapTools, but I can't extract the methylation haplotypes from the alignment result, I would like to know if mHaplotype only process the alignment results generated by BISMARK or BSMAP.

**Comment by butyuhao** [comment]
Hello, mHapTools can process  all the data in BS-seq format. Please make sure your input data is methylation data. : )

**Comment by EnyangQiao** [comment]
Hi, Yuhao.

Thanks very much for your replying.  I am sure my data was methylation data, but I suffered some problems when using mHapTools to do methylation haplotypes. I watched the manual and confused the CpG.gz file, and I am not sure if the Python script annotation_files.py generated the CpG.gz file.
Do you mind if I add your WeChat to ask you about this problem?  I would like to consult you about mHapTools.

I look forward to hearing from you.

Best wishes,
Enyang Qiao
From: 但宇豪 ***@***.***>
Date: Wednesday, 15 September 2021 at 11:52
To: butyuhao/mHapTools ***@***.***>
Cc: Enyang Qiao (student) ***@***.***>, Author ***@***.***>
Subject: Re: [butyuhao/mHapTools] The using requirement of mHapTools (#1)

Hello, mHapTools can process all the data in BS-seq format. Please make sure your input data is methylation data. : )

**Comment by butyuhao** [comment]
Sure, my wechat id: butyuhao
